column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
# TODO: Switch to 2 after merging
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
