version: '3'
services:
  restapi:
    image: usage-tracker-restapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./sqlite_db:/app/data

        # volumes:
        #   restapi-volume:

